spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_rental
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

app:
  jwtSecret: secretKey
  jwtExpirationInMs: 86400000

